//
//  LoginPresenter.swift
//  VIP Architecture
//
//  Created by haoxian on 2018/4/19.
//  Copyright (c) 2018年 haoxian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

/// Interactor output
protocol LoginPresentationLogic {
  func presentLoginResult(_ response: Login.LoginEvent.Response)
}

class LoginPresenter {
  weak var viewController: LoginDisplayLogic?
}
/// 遵循协议，作为Interactor 的 output
extension LoginPresenter: LoginPresentationLogic {
  func presentLoginResult(_ response: Login.LoginEvent.Response) {
    let viewModel = Login.LoginEvent.ViewModel(success: response.success, errorMsg: response.errorMsg)
    if viewModel.success {
      self.viewController?.loginSuccessed(viewModel: viewModel)
    } else {
      self.viewController?.loginFailed(viewModel: viewModel)
    }
  }
}
