//
//  LoginModels.swift
//  VIP Architecture
//
//  Created by haoxian on 2018/4/19.
//  Copyright (c) 2018年 haoxian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum Login {}

extension Login {
  // 登录事件
  enum LoginEvent
  {
    struct Request
    {
      let account: String?
      let password: String?
    }
    struct Response: Codable
    {
      let user: User?
      let success: Bool
      let errorMsg: String?
    }
    struct ViewModel
    {
      let success: Bool
      let errorMsg: String?
    }
  }
}

//extension Login {
//  // 其他事件
//  enum otherEvent {
//    struct Request {
//
//    }
//    struct Response {
//
//    }
//    struct ViewModel {
//      
//    }
//  }
//}
