//
//  LoginRouter.swift
//  VIP Architecture
//
//  Created by haoxian on 2018/4/19.
//  Copyright (c) 2018年 haoxian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
  func toMainView()
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginDataPassing {
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
}

extension LoginRouter: LoginRoutingLogic {
  func toMainView() {
    let mainView = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MainViewController") as! MainViewController
    /// 这里传值例子只是用于强行演示，实际开发中是不采取这种形式
    mainView.user = dataStore?.user
    UIApplication.shared.keyWindow?.rootViewController = mainView
  }
}
